#!/bin/bash  

#
#SOURCE_PATH Path to the vmdk
#SOURCE to contain the attached block device to convert (flat vmdk)
#TEMPFOLDER to contain a path (/data)
#DEST Device of the zcompute volume - target device
#
#
SOURCE_PATH=$1
SOURCE_VMDK=$2
TEMPFOLDER=$3
DEST=$4
rm -f $TEMPFOLDER/$SOURCE_VMDK-flat-sda
ntfsfix -d $SOURCE_VMDK
export LIBGUESTFS_BACKEND_SETTINGS=force_tcg ; export LIBGUESTFS_CACHEDIR=$TEMPFOLDER ;  virt-v2v -i disk $SOURCE_PATH/$SOURCE_VMDK-flat.vmdk -o local -os $TEMPFOLDER
#This may take a while 
dd if=$TEMPFOLDER/$SOURCE_VMDK-flat-sda bs=128M | pv | dd of=/dev/$DEST bs=128M
sync
